### ISSUE TITLE
vRA v8 support

### ISSUE THREAD

**Issue by jayhendren** [test-kitchen/vmware-vra-gem#83]
This is a request to add support for vRA v8.

**Comment by vkarve-chef** [comment]
- API calls are updated so that the wrapper methods work with vRA 8.x. 
- Backward compatibility with vRA 7.x is maintained. 
- Tests are updated to cover the code changes.

**Comment by vkarve-chef** [comment]
@jayhendren you may want to check out the latest version of the gem. we've updated it to support vRA8. if the gem works for you, could you please mark the issue as Closed?

**Comment by tas50** [comment]
This shipped as 3.0

**Comment by jayhendren** [comment]
> @jayhendren you may want to check out the latest version of the gem. we've updated it to support vRA8. if the gem works for you, could you please mark the issue as Closed?

For several reasons, including this issue, I long ago abandoned the project that would've used this gem.  So I doubt I'll get around to testing this soon.  Thanks for addressing this and letting me know.
